# Site
title: Janet Joy Wilson
description: "Janet Joy Wilson is an activist, consultant and creative coach. Janet's goal is to make the world a better place: one book and one bike lane at a time."
about: "ac·tiv·ist, consultant, coach, marketing guru"
url: https://janetjoywilson.ca
logo: logo.png # Site logo
locale: en_US
future: false

google-analytics: UA-79717942-2

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    enable_coderay: false

# Left Block Images
background:
    homepage: images/home.png # this image will be shown on homepage's left block
    post-list: images/bookshelf.jpg # this image will be shown on post list page
    default-post: images/toronto.jpg # this image will be shown when post's front matter doesn't specify any image

# Collections
collections:
    projects:
        permalink: /projects/:title/
    library:
        output: true
        permalink: /library/:title/

# Style
sass:
    sass_dir: assets/_sass
    style: compressed

# Social Links
email: janetjoywilsonca@gmail.com
twitter: jsquaredink
facebook: janet.j.wilson.94
linkedin: janet-joy-wilson-0598a926
instagram: jsquaredink

repository: janetjoywilson/janetjoywilson.github.io

include: [_pages]
